version: "3.8"

services:
  postgres:
    image: postgres:16.0
    container_name: llama_gamer_postgres
    restart: always
    environment:
      POSTGRES_DB: llama_gamer_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: "UTC-4"
    ports:
      - 3030:3030
    command: -p 3030
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.pgsql:/docker-entrypoint-initdb.d/1.sql

  api-gateway:
    container_name: gateway
    build:
      context: ./projects/
      dockerfile: ./gateway/Dockerfile
    network_mode: "host"
    environment:
      - NGINX_PORT=8000


  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: llama_gamer_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 4040
    ports:
      - 4040:4040
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres


  mongodb:
    image: mongo:latest
    container_name: llama_gamer_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: productsdb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
    restart: always

volumes:
  pgadmin-data:
  postgres-data:
  mongodb-data:
